apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels: 
    component: web
spec:
  containers:
  - name: memory-demo-ctr
    image: stephengrider/multi-worker
    ports: 
      - containerPort: 3000
    resources:
      limits:
        memory: "200Mi"
      requests:
        memory: "100Mi"

