sudo: required
services:
  - docker

env:
  global:
    - SHA = $(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  # TODO use AES do decrypt gcp service account
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project <project-id>
  - gcloud config set compute/zone <zone>
  - gcloud container clusters get-credentials <cluster name>
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t 155663/react-test -f ./client/Dockerfile.dev  ./client
script:
  - docker run -e CI=true aviadshiber/docker-react npm run test -- --coverage

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master  